# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado_workspace/SDHCAL_DAQ2V0_latest/Constraints/SDHCAL_DAQ2V0.xdc

# IP: ip/usb_data_fifo/usb_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usb_data_fifo || ORIG_REF_NAME==usb_data_fifo}]

# XDC: ip/usb_data_fifo/usb_data_fifo/usb_data_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==usb_data_fifo || ORIG_REF_NAME==usb_data_fifo}] {/U0 }]/U0 ]]

# XDC: ip/usb_data_fifo/usb_data_fifo/usb_data_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==usb_data_fifo || ORIG_REF_NAME==usb_data_fifo}] {/U0 }]/U0 ]]
