# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SDHCAL_DIF_1V0.xdc

# IP: ip/CommandFifo/CommandFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CommandFifo || ORIG_REF_NAME==CommandFifo} -quiet] -quiet

# IP: ip/ConfigParameterFIFO/ConfigParameterFIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ConfigParameterFIFO || ORIG_REF_NAME==ConfigParameterFIFO} -quiet] -quiet

# IP: ip/SCurveDataFifo/SCurveDataFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCurveDataFifo || ORIG_REF_NAME==SCurveDataFifo} -quiet] -quiet

# IP: ip/MicrorocChainDataFifo/MicrorocChainDataFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicrorocChainDataFifo || ORIG_REF_NAME==MicrorocChainDataFifo} -quiet] -quiet

# IP: ip/ExternalDataFifo/ExternalDataFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ExternalDataFifo || ORIG_REF_NAME==ExternalDataFifo} -quiet] -quiet

# XDC: ip/CommandFifo/CommandFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CommandFifo || ORIG_REF_NAME==CommandFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/CommandFifo/CommandFifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CommandFifo || ORIG_REF_NAME==CommandFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ConfigParameterFIFO/ConfigParameterFIFO.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ConfigParameterFIFO || ORIG_REF_NAME==ConfigParameterFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ConfigParameterFIFO/ConfigParameterFIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ConfigParameterFIFO || ORIG_REF_NAME==ConfigParameterFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/SCurveDataFifo/SCurveDataFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SCurveDataFifo || ORIG_REF_NAME==SCurveDataFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/MicrorocChainDataFifo/MicrorocChainDataFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicrorocChainDataFifo || ORIG_REF_NAME==MicrorocChainDataFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ExternalDataFifo/ExternalDataFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ExternalDataFifo || ORIG_REF_NAME==ExternalDataFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ExternalDataFifo/ExternalDataFifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ExternalDataFifo || ORIG_REF_NAME==ExternalDataFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
