# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.cache/wt [current_project]
set_property parent.project_path D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AsicRamReadout.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AutoDaq.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/BitShiftOut.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/CommandDecoder.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/CommandInterpreter.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/ConfigurationParameterDistribution.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/DaqControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/DaqSwitcher.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/ExternalRazGenerate.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/HoldGenerate.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/MicrorocControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/ParameterGenerator.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/PowerOnControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/PulseSynchronous.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/Redundancy.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SlaveDaq.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SlowControlAndReadScopeSet.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/TimeStampSyncAndDataTrigger.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/usb_synchronous_slavefifo.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/FPGA_Top.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SCurve_Test_Control.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SCurve_Test_Top.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SCurve_Single_Test.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SCurve_Single_Input.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/ADC_AD9220.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AdcControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AcquisitionControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AcquisitionSwitcher.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/TriggerSwitcher.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/ClockManagement.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/MicrorocDataSwitcher.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/MicrorocCommonControl.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/RamReadDoneSync4Chain.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/SpiMaster.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/DacControlTlv5618.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/AutoCalibrationSignalGen.v
  D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/src/CalibrationSwitcherControl.v
}
read_ip -quiet D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/CommandFifo/CommandFifo.xci
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/CommandFifo/CommandFifo.xdc]
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/CommandFifo/CommandFifo_clocks.xdc]

read_ip -quiet D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ConfigParameterFIFO/ConfigParameterFIFO.xci
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ConfigParameterFIFO/ConfigParameterFIFO.xdc]
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ConfigParameterFIFO/ConfigParameterFIFO_clocks.xdc]

read_ip -quiet D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/SCurveDataFifo/SCurveDataFifo.xci
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/SCurveDataFifo/SCurveDataFifo.xdc]

read_ip -quiet D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/MicrorocChainDataFifo/MicrorocChainDataFifo.xci
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/MicrorocChainDataFifo/MicrorocChainDataFifo.xdc]

read_ip -quiet D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ExternalDataFifo/ExternalDataFifo.xci
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ExternalDataFifo/ExternalDataFifo.xdc]
set_property used_in_implementation false [get_files -all d:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/sources_1/ip/ExternalDataFifo/ExternalDataFifo_clocks.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/constrs_1/new/SDHCAL_DIF_1V0.xdc
set_property used_in_implementation false [get_files D:/MyProject/SDHCAL_DAQ/SDHCAL_DIF1V0/SDHCAL_DIF1V0.srcs/constrs_1/new/SDHCAL_DIF_1V0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top FPGA_Top -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FPGA_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FPGA_Top_utilization_synth.rpt -pb FPGA_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
