set_property SRC_FILE_INFO {cfile:D:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.runs/synth_1/.Xil/Vivado-14712-WYU/dcp/param_store_fifo_in_context.xdc rfile:../dcp/param_store_fifo_in_context.xdc id:1 order:EARLY scoped_inst:Microroc_u1/SC_Readreg/param_store_fifo_16bitx256deep} [current_design]
set_property SRC_FILE_INFO {cfile:D:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.runs/synth_1/.Xil/Vivado-14712-WYU/dcp_2/usb_cmd_fifo_in_context.xdc rfile:../dcp_2/usb_cmd_fifo_in_context.xdc id:2 order:EARLY scoped_inst:usb_control/usbcmdfifo_16depth} [current_design]
set_property SRC_FILE_INFO {cfile:D:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.runs/synth_1/.Xil/Vivado-14712-WYU/dcp_3/SCurve_Data_FIFO_in_context.xdc rfile:../dcp_3/SCurve_Data_FIFO_in_context.xdc id:3 order:EARLY scoped_inst:Microroc_Control/Microroc_SCurveTest/scurve_data_fifo_16x16} [current_design]
set_property SRC_FILE_INFO {cfile:D:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/Constraints/SDHCAL_DAQ2V0.xdc rfile:../../../../../Constraints/SDHCAL_DAQ2V0.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:D:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:d:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SweepACQ_FIFO/SweepACQ_FIFO/SweepACQ_FIFO.xdc rfile:../../../../../SDHCAL_DAQ2V0.srcs/sources_1/ip/SweepACQ_FIFO/SweepACQ_FIFO/SweepACQ_FIFO.xdc id:6 order:EARLY scoped_inst:Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/MyProject/SDHCAL_DAQ/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/usb_data_fifo/usb_data_fifo/usb_data_fifo.xdc rfile:../../../../../SDHCAL_DAQ2V0.srcs/sources_1/ip/usb_data_fifo/usb_data_fifo/usb_data_fifo.xdc id:7 order:EARLY scoped_inst:usb_data_fifo_8192depth/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Microroc_u1/SC_Readreg/param_store_fifo_16bitx256deep/rd_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Microroc_u1/SC_Readreg/param_store_fifo_16bitx256deep/wr_clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Microroc_u1/SC_Readreg/param_store_fifo_16bitx256deep]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins usb_control/usbcmdfifo_16depth/rd_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins usb_control/usbcmdfifo_16depth/wr_clk]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells usb_control/usbcmdfifo_16depth]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Microroc_Control/Microroc_SCurveTest/scurve_data_fifo_16x16/clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Microroc_Control/Microroc_SCurveTest/scurve_data_fifo_16x16]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Clk_40M]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[0]}]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[1]}]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[2]}]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[3]}]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[4]}]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[5]}]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports CK_5P]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports CK_5N]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports CK_40N]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports CK_40P]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_clkout]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_ifclk]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[15]}]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[14]}]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[13]}]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[12]}]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[11]}]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[10]}]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[9]}]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[8]}]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[7]}]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[6]}]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[5]}]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[4]}]
set_property src_info {type:XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[3]}]
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[2]}]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[1]}]
set_property src_info {type:XDC file:4 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[0]}]
set_property src_info {type:XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[1]}]
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[0]}]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CHIPSATB]
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports DOUT1B]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports DOUT2B]
set_property src_info {type:XDC file:4 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports END_READOUT1]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports END_READOUT2]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports HOLD]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_TRIG0B]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_TRIG1B]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_TRIG2B]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PWR_ON_A]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PWR_ON_ADC]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PWR_ON_D]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PWR_ON_DAC]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports RAZ_CHNP]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports RAZ_CHNN]
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports RESET_B]
set_property src_info {type:XDC file:4 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports RST_COUNTERB]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SELECT]
set_property src_info {type:XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SR_CK]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SR_IN]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SR_RSTB]
set_property src_info {type:XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports START_ACQ]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports START_READOUT1]
set_property src_info {type:XDC file:4 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports START_READOUT2]
set_property src_info {type:XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TRANSMITON1B]
set_property src_info {type:XDC file:4 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TRANSMITON2B]
set_property src_info {type:XDC file:4 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TRIG_EXT]
set_property src_info {type:XDC file:4 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_flaga]
set_property src_info {type:XDC file:4 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_flagb]
set_property src_info {type:XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_flagc]
set_property src_info {type:XDC file:4 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_pktend]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_slcs]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_sloe]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_slrd]
set_property src_info {type:XDC file:4 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_slwr]
set_property src_info {type:XDC file:4 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports VAL_EVTP]
set_property src_info {type:XDC file:4 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports VAL_EVTN]
set_property src_info {type:XDC file:4 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_TRIGB]
set_property src_info {type:XDC file:4 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property ASYNC_REG true [get_cells usb_cy7c68013A/Acq_Start_Stop_sync1_reg]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property ASYNC_REG true [get_cells usb_cy7c68013A/Acq_Start_Stop_sync2_reg]
set_property src_info {type:XDC file:4 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {TP[3]}]
set_property src_info {type:XDC file:4 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {TP[2]}]
set_property src_info {type:XDC file:4 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {TP[1]}]
set_property src_info {type:XDC file:4 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {TP[0]}]
set_property src_info {type:XDC file:4 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADG804_Addr[1]}]
set_property src_info {type:XDC file:4 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADG804_Addr[0]}]
set_property src_info {type:XDC file:4 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ADG819_Addr]
set_property src_info {type:XDC file:4 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_EXT]
set_property src_info {type:XDC file:4 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[10]}]
set_property src_info {type:XDC file:4 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[4]}]
set_property src_info {type:XDC file:4 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[3]}]
set_property src_info {type:XDC file:4 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[6]}]
set_property src_info {type:XDC file:4 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[9]}]
set_property src_info {type:XDC file:4 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[1]}]
set_property src_info {type:XDC file:4 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[7]}]
set_property src_info {type:XDC file:4 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[0]}]
set_property src_info {type:XDC file:4 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[8]}]
set_property src_info {type:XDC file:4 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[11]}]
set_property src_info {type:XDC file:4 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[12]}]
set_property src_info {type:XDC file:4 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[15]}]
set_property src_info {type:XDC file:4 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[14]}]
set_property src_info {type:XDC file:4 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[13]}]
set_property src_info {type:XDC file:4 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[2]}]
set_property src_info {type:XDC file:4 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_debug[5]}]
set_property src_info {type:XDC file:4 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[0]}]
set_property src_info {type:XDC file:4 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[4]}]
set_property src_info {type:XDC file:4 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[9]}]
set_property src_info {type:XDC file:4 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[10]}]
set_property src_info {type:XDC file:4 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[1]}]
set_property src_info {type:XDC file:4 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[13]}]
set_property src_info {type:XDC file:4 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[14]}]
set_property src_info {type:XDC file:4 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[12]}]
set_property src_info {type:XDC file:4 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[15]}]
set_property src_info {type:XDC file:4 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[11]}]
set_property src_info {type:XDC file:4 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[3]}]
set_property src_info {type:XDC file:4 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[8]}]
set_property src_info {type:XDC file:4 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[6]}]
set_property src_info {type:XDC file:4 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[5]}]
set_property src_info {type:XDC file:4 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[7]}]
set_property src_info {type:XDC file:4 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_din_debug[2]}]
set_property src_info {type:XDC file:4 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets Microroc_Control/Microroc_SCurveTest/SCurve_Data_wr_en_debug]
set_property src_info {type:XDC file:4 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets Microroc_Control/Microroc_SCurveTest/SCurve_Data_fifo_rd_en_debug]
set_property src_info {type:XDC file:4 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[11]}]
set_property src_info {type:XDC file:4 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[10]}]
set_property src_info {type:XDC file:4 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[9]}]
set_property src_info {type:XDC file:4 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[8]}]
set_property src_info {type:XDC file:4 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[7]}]
set_property src_info {type:XDC file:4 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[6]}]
set_property src_info {type:XDC file:4 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[5]}]
set_property src_info {type:XDC file:4 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[4]}]
set_property src_info {type:XDC file:4 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[3]}]
set_property src_info {type:XDC file:4 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[2]}]
set_property src_info {type:XDC file:4 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[1]}]
set_property src_info {type:XDC file:4 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[0]}]
set_property src_info {type:XDC file:4 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CLK]
set_property src_info {type:XDC file:4 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_OTR]
set_property src_info {type:XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0]
set_property src_info {type:XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells usb_data_fifo_8192depth/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells Microroc_Control/Microroc_SCurveTest/scurve_data_fifo_16x16]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells usb_data_fifo_8192depth]
set_property src_info {type:SCOPED_XDC file:6 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/rst] -to [get_pins [list Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/grstd1.grst_full.grst_f.rst_d1_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/grstd1.grst_full.grst_f.rst_d2_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/grstd1.grst_full.grst_f.rst_d3_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_asreg_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg2_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg2_reg/PRE Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_asreg_reg/PRE {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[0]/PRE} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[1]/PRE} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[2]/PRE} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[0]/PRE} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[1]/PRE} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[2]/PRE}]]
set_property src_info {type:SCOPED_XDC file:6 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells [list {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[0]} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[1]} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[2]} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[0]} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[1]} {Microroc_Control/SweepACQ/SweepACQ_DataFIFO16x128/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[2]}]]
set_property src_info {type:SCOPED_XDC file:7 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins usb_data_fifo_8192depth/U0/rst] -to [get_pins [list usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_asreg_reg/PRE usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg/PRE usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg2_reg/PRE usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg/PRE usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg2_reg/PRE usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_asreg_reg/PRE {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[0]/PRE} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[1]/PRE} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[2]/PRE} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[0]/PRE} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[1]/PRE} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[2]/PRE}]]
set_property src_info {type:SCOPED_XDC file:7 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells [list {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[0]} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[1]} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rd_rst_reg_reg[2]} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[0]} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[1]} {usb_data_fifo_8192depth/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.wr_rst_reg_reg[2]}]]
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 25.000 -name Clk_40M -waveform {0.000 12.500} [get_ports Clk_40M]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports rst_n]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports rst_n]
set_property src_info {type:XDC file:4 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.833 -name usb_clkout -waveform {0.000 10.417} [get_ports usb_clkout]
set_property src_info {type:XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports CHIPSATB]
set_property src_info {type:XDC file:4 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports CHIPSATB]
set_property src_info {type:XDC file:4 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports DOUT1B]
set_property src_info {type:XDC file:4 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports DOUT1B]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports DOUT2B]
set_property src_info {type:XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports DOUT2B]
set_property src_info {type:XDC file:4 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports END_READOUT1]
set_property src_info {type:XDC file:4 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports END_READOUT1]
set_property src_info {type:XDC file:4 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports END_READOUT2]
set_property src_info {type:XDC file:4 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports END_READOUT2]
set_property src_info {type:XDC file:4 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports TRANSMITON1B]
set_property src_info {type:XDC file:4 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports TRANSMITON1B]
set_property src_info {type:XDC file:4 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports TRANSMITON2B]
set_property src_info {type:XDC file:4 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports TRANSMITON2B]
set_property src_info {type:XDC file:4 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -min -add_delay 10.000 [get_ports usb_flaga]
set_property src_info {type:XDC file:4 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -max -add_delay 15.000 [get_ports usb_flaga]
set_property src_info {type:XDC file:4 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -min -add_delay 10.000 [get_ports usb_flagb]
set_property src_info {type:XDC file:4 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -max -add_delay 15.000 [get_ports usb_flagb]
set_property src_info {type:XDC file:4 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -min -add_delay 10.000 [get_ports usb_flagc]
set_property src_info {type:XDC file:4 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks usb_clkout] -max -add_delay 15.000 [get_ports usb_flagc]
set_property src_info {type:XDC file:4 line:175 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 200.000 -name VIRTUAL_pll_5 -waveform {0.000 100.000}
set_property src_info {type:XDC file:4 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports {LED[*]}]
set_property src_info {type:XDC file:4 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports {LED[*]}]
set_property src_info {type:XDC file:4 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports PWR_ON_A]
set_property src_info {type:XDC file:4 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports PWR_ON_A]
set_property src_info {type:XDC file:4 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports PWR_ON_ADC]
set_property src_info {type:XDC file:4 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports PWR_ON_ADC]
set_property src_info {type:XDC file:4 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports PWR_ON_D]
set_property src_info {type:XDC file:4 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports PWR_ON_D]
set_property src_info {type:XDC file:4 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports PWR_ON_DAC]
set_property src_info {type:XDC file:4 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports PWR_ON_DAC]
set_property src_info {type:XDC file:4 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports RAZ_CHNN]
set_property src_info {type:XDC file:4 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports RAZ_CHNN]
set_property src_info {type:XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports RAZ_CHNP]
set_property src_info {type:XDC file:4 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports RAZ_CHNP]
set_property src_info {type:XDC file:4 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports RESET_B]
set_property src_info {type:XDC file:4 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports RESET_B]
set_property src_info {type:XDC file:4 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports RST_COUNTERB]
set_property src_info {type:XDC file:4 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports RST_COUNTERB]
set_property src_info {type:XDC file:4 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports SELECT]
set_property src_info {type:XDC file:4 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports SELECT]
set_property src_info {type:XDC file:4 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -min -add_delay 6.000 [get_ports SR_CK]
set_property src_info {type:XDC file:4 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -max -add_delay 100.000 [get_ports SR_CK]
set_property src_info {type:XDC file:4 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -min -add_delay 6.000 [get_ports SR_IN]
set_property src_info {type:XDC file:4 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -max -add_delay 100.000 [get_ports SR_IN]
set_property src_info {type:XDC file:4 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -min -add_delay 6.000 [get_ports SR_RSTB]
set_property src_info {type:XDC file:4 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_pll_5] -max -add_delay 100.000 [get_ports SR_RSTB]
set_property src_info {type:XDC file:4 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports START_ACQ]
set_property src_info {type:XDC file:4 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports START_ACQ]
set_property src_info {type:XDC file:4 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports START_READOUT1]
set_property src_info {type:XDC file:4 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports START_READOUT1]
set_property src_info {type:XDC file:4 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports START_READOUT2]
set_property src_info {type:XDC file:4 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports START_READOUT2]
set_property src_info {type:XDC file:4 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -min -add_delay 2.000 [get_ports TRIG_EXT]
set_property src_info {type:XDC file:4 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_40M] -max -add_delay 12.000 [get_ports TRIG_EXT]
set_property src_info {type:XDC file:4 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -min -add_delay 2.000 [get_ports usb_pktend]
set_property src_info {type:XDC file:4 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -max -add_delay 10.000 [get_ports usb_pktend]
set_property src_info {type:XDC file:4 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -min -add_delay 2.000 [get_ports usb_sloe]
set_property src_info {type:XDC file:4 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -max -add_delay 10.000 [get_ports usb_sloe]
set_property src_info {type:XDC file:4 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -min -add_delay 2.000 [get_ports usb_slrd]
set_property src_info {type:XDC file:4 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -max -add_delay 10.000 [get_ports usb_slrd]
set_property src_info {type:XDC file:4 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -min -add_delay 2.000 [get_ports usb_slwr]
set_property src_info {type:XDC file:4 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks usb_clkout] -max -add_delay 10.000 [get_ports usb_slwr]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name feedback -source [get_pins Clk_Gen/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock Clk_40M [get_pins Clk_Gen/MMCME2_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_40 -source [get_pins Clk_Gen/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock Clk_40M [get_pins Clk_Gen/MMCME2_BASE_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_5 -source [get_pins Clk_Gen/MMCME2_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 87.500 175.000} -add -master_clock Clk_40M [get_pins Clk_Gen/MMCME2_BASE_inst/CLKOUT2]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name Clk_320M -source [get_pins Clk_Gen/MMCME2_BASE_inst/CLKIN1] -multiply_by 4 -add -master_clock Clk_40M [get_pins Clk_Gen/MMCME2_BASE_inst/CLKOUT3]
set_property src_info {type:XDC file:4 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks usb_clkout] -to [get_clocks pll_40]
set_property src_info {type:XDC file:4 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks pll_40] -group [get_clocks usb_clkout]
set_property src_info {type:XDC file:4 line:319 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 6.250 -name Clk_320M -waveform {0.000 3.125} [get_nets Clk_320M]
set_property src_info {type:XDC file:4 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks Clk_320M] -add_delay 0.000 [get_ports HOLD]
set_property src_info {type:XDC file:4 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_320M] -add_delay 0.000 [get_ports OUT_TRIG0B]
set_property src_info {type:XDC file:4 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_320M] -add_delay 0.000 [get_ports OUT_TRIG1B]
set_property src_info {type:XDC file:4 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_320M] -add_delay 0.000 [get_ports OUT_TRIG2B]
set_property src_info {type:XDC file:4 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_320M] -add_delay 0.000 [get_ports EXT_TRIGB]
set_property src_info {type:XDC file:4 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports {{ADC_DATA[0]} {ADC_DATA[1]} {ADC_DATA[2]} {ADC_DATA[3]} {ADC_DATA[4]} {ADC_DATA[5]} {ADC_DATA[6]} {ADC_DATA[7]} {ADC_DATA[8]} {ADC_DATA[9]} {ADC_DATA[10]} {ADC_DATA[11]}}]
set_property src_info {type:XDC file:4 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports {{ADC_DATA[0]} {ADC_DATA[1]} {ADC_DATA[2]} {ADC_DATA[3]} {ADC_DATA[4]} {ADC_DATA[5]} {ADC_DATA[6]} {ADC_DATA[7]} {ADC_DATA[8]} {ADC_DATA[9]} {ADC_DATA[10]} {ADC_DATA[11]}}]
set_property src_info {type:XDC file:4 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -max -add_delay 18.000 [get_ports ADC_OTR]
set_property src_info {type:XDC file:4 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks Clk_40M] -min -add_delay 12.000 [get_ports ADC_OTR]
