% filename = 'Charge_vs_ShaperOut20170110.xlsx';
% sheet = 1;
% xlRange = 'A2:D26';
% subsetA = xlsread(filename,sheet,xlRange);
A = uiimport('-file');
subsetA = A.data;
Charge = subsetA(:,1)';
Vout_min1 = subsetA(:,2)';
Vout_min2 = subsetA(:,3)';
Vout_min3 = subsetA(:,3)';
Vout_minAve = (Vout_min1 + Vout_min2 + Vout_min3)/3.0;
deltaV = 2.143 - Vout_minAve;
Rp = corrcoef(Charge, deltaV);
R = Rp(2,1);
x = linspace(min(Charge),max(Charge));
p0 = polyfit(Charge,deltaV,1);
y0 = polyval(p0,x);
figure(1);
plot(Charge,deltaV,'x');
hold on;
plot(x,y0);
str0 = sprintf('Charge vs High Gain Shaper output \\DeltaV\n--The Linear correlation coefficient is %1.6f',R');
cal = legend(str0);
set(cal,'Location','northwest');
xlabel('Inject Charge (fC)');
ylabel('\DeltaV (V)');
hold off;

deltaV_Polyfit = p0(1)*Charge + p0(2);
Deviation_Polyfit = (deltaV - deltaV_Polyfit)/max(deltaV_Polyfit);
% Deviation_Polyfit = abs(deltaV - deltaV_Polyfit);
Percent_Dev_Polyfit = Deviation_Polyfit .* 100;

figure(2);
plot(Charge,Percent_Dev_Polyfit,'bo');
hold on;
plot(Charge,Percent_Dev_Polyfit,'k');
xlabel('Inject Charge(fC)');
ylabel('偏离线性的比例(%)');
xAxisS = 0;
xAxisE = 520;
yAxisS = min(Percent_Dev_Polyfit)*2;
yAxisE = max(Percent_Dev_Polyfit)*2;
axis([xAxisS inf yAxisS yAxisE]);
xtext = xAxisE/4;
ytext = yAxisS + (yAxisE-yAxisS)/5;
strOut1 = sprintf('$$\\frac{Vout_{Measure} - Vout_{Linear fit}}{Vout(max)}$$');
text('Interpreter','latex','String',strOut1,'Position',[xtext,ytext],'FontSize',14,'Color','r');
h = legend('$$\frac{Vout_{Measure} - Vout_{Linear fit}}{Vout(max)} vs Charge $$');
set(h,'Interpreter','latex','Location','northeast');
hold on;
t = [xAxisS,xAxisE];
y = [0,0];
plot(t,y,'k');