# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo.xci
# IP: The module: 'param_store_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo/param_store_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo/param_store_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo.xci
# IP: The module: 'param_store_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo/param_store_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo/param_store_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Vivado_workspace/SDHCAL_DAQ2V0/SDHCAL_DAQ2V0.srcs/sources_1/ip/param_store_fifo/param_store_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'param_store_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
