# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO.xci
# IP: The module: 'SCurve_Data_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO/SCurve_Data_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCurve_Data_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCurve_Data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO.xci
# IP: The module: 'SCurve_Data_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO/SCurve_Data_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCurve_Data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado_workspace/SDHCAL_DAQ2V0_SCurveTest/SDHCAL_DAQ2V0.srcs/sources_1/ip/SCurve_Data_FIFO/SCurve_Data_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCurve_Data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
